### ISSUE TITLE
Quickmatch takes much longer time when caliper is not null

### ISSUE THREAD

**Issue by yuany94** [fsavje/quickmatch#14]

**Comment by fsavje** [comment]
Thanks for the report @yuany94 . The reason the package is slower with a caliper is because the [ANN](https://www.cs.umd.edu/~mount/ANN/) package, which is part of quickmatch, is slower when doing exact nearest neighbor search with a radius constraint. The purpose of the caliper in quickmatch is not to decrease run time.

How large is the data set you are trying to match?

**Comment by yuany94** [comment]
I have ~50k treatments and millions of potential control. Without a caliper, it is really fast, but otherwise my code seems not to stop. Is there any way that I can first match without caliper and then remove those matched pairs with too far distances? Thanks.

**Comment by fsavje** [comment]
How are you calling the quickmatch function? I would recommend using the `target` parameter when you have so many more control units. For example:

```
my_data <- data.frame(y = rnorm(10000),
                      x1 = runif(10000),
                      x2 = runif(10000),
                      treated = as.logical(rbinom(10000, 1, 0.02)))

my_distances <- distances(my_data, dist_variables = c("x1", "x2"))

matching <- quickmatch(my_distances, my_data$treated, target = my_data$treated, caliper = 0.1)
```

Please note that the caliper in quickmatch is somewhat different from a standard caliper. In particular, the caliper imposes constraints on the edges in the graph of the underlying clustering problem solved by the `sc_clustering` function in the `scclust` package. The parameters `seed_radius`, `primary_radius` and `secondary_radius` for that function can often be tweaked to get better performance either in run time or match quality. The `caliper` parameter in quickmatch sets these parameters for the sc_clustering function to emulate a traditional caliper.

Please let me know how this works out.

**Comment by fsavje** [comment]
Using the `target` parameter as above presumes that you are estimating the average treatment effect on the treated (ATT). If you want to estimate an ATE, them you need to target all units.

**Comment by yuany94** [comment]
Yes, I realize that ATT is much faster when treatment/control groups are unbalanced. Thanks.
